variable "env" {}
variable "components" {}
variable "tags" {}
variable "VPC" {}
variable "default_VPC_id" {}
variable "default_Route_table_ID" {}
variable "rabbitmq" {}
variable "bastion_host" {}
variable "zone_id" {}
variable "rds" {}
variable "kms_key_id" {}
variable "documentdb" {}
variable "elasticache" {}
variable "alb" {}
variable "apps" {}
variable "allow_prometheus" {}